### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by disowned** [adawolfa/etwsl#1]
I have a problem, i don't know how to use this i just get a blank page. Please tell me how to use this.

**Comment by adawolfa** [comment]
Hello, this project is just a PHP library, not a widget. That means it requires some programming knowledge and you have to build an interface on your own. For widgets, try GameTracker!

**Comment by adawolfa** [comment]
Just in case you have asked just for that, here are some steps:

1. Download source or install it using Composer.
2. Include the `src/MasterQuery.php`, `src/ServerQuery.php` or `vendor/autoload.php` generated by Composer.
3. Follow the examples in readme file.
